Fix regression when saving binary data
spec.services.business_partners.update_request_csv_processor_spec.BusinessPartners::UpdateRequestCsvProcessor processes the CSV and updates business partners correctly

Error Details
com.microsoft.sqlserver.jdbc.SQLServerException: Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
 Stack Trace
Failure/Error: @request.update!(result_csv: csv_data)

ActiveRecord::JDBCError:
  com.microsoft.sqlserver.jdbc.SQLServerException: Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
arjdbc/jdbc/RubyJdbcConnection.java:921:in `execute_insert_pk'
arjdbc/mssql/MSSQLRubyJdbcConnection.java:255:in `execute_insert_pk'
/root/.gem/jruby/3.1.0/gems/fm_base-11.14.3/lib/active_record/extensions/binary_column_table.rb:68:in `block in has_binary_columns'
./app/services/business_partners/update_request_csv_processor.rb:95:in `save_result_csv'
./app/services/business_partners/update_request_csv_processor.rb:36:in `process!'
./spec/services/business_partners/update_request_csv_processor_spec.rb:73:in `block in <main>'
------------------
--- Caused by: ---
Java::ComMicrosoftSqlserverJdbc::SQLServerException:
  Implicit conversion from data type nvarchar to varbinary(max) is not allowed. Use the CONVERT function to run this query.
  com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)