Mssql, fix FrozenError: can't modify frozen object
issue cause by freezing object after initialization in AR code

Error: test_using_named_savepoints(MSSQLTransactionTest): FrozenError: can't modify frozen ActiveRecord::ConnectionAdapters::MSSQL::Type::NvarcharMax: #<ActiveRecord::ConnectionAdapters::MSSQL::Type::NvarcharMax:0x32ddcca @limit=nil, @true="t", @false="f", @scale=nil, @precision=nil>
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/types/string_types.rb:51:in 'limit'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:1774:in 'fetch_type_metadata'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/schema_statements.rb:423:in 'fetch_type_metadata'
arjdbc/jdbc/RubyJdbcConnection.java:1343:in 'columns'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/adapter.rb:518:in 'block in column_definitions'
/home/jessec/bryk/vendor/rails/activesupport/lib/active_support/notifications/instrumenter.rb:58:in 'instrument'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:1213:in 'log'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/adapter.rb:518:in 'column_definitions'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:110:in 'columns'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:345:in 'block in columns'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:459:in 'with_connection'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:344:in 'block in columns'
org/jruby/RubyHash.java:1539:in 'fetch'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:343:in 'columns'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:354:in 'block in columns_hash'
org/jruby/RubyHash.java:1539:in 'fetch'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:353:in 'columns_hash'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:54:in 'columns_hash'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:198:in 'columns_hash'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/model_schema.rb:609:in 'load_schema!'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/counter_cache.rb:214:in 'load_schema!'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/encryption/encryptable_record.rb:127:in 'load_schema!'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/model_schema.rb:555:in 'block in load_schema'
org/jruby/ext/monitor/Monitor.java:85:in 'synchronize'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/model_schema.rb:552:in 'load_schema'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/model_schema.rb:444:in 'columns_hash'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/attributes.rb:257:in 'block in _default_attributes'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:459:in 'with_connection'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_handling.rb:313:in 'with_connection'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/attributes.rb:256:in '_default_attributes'
/home/jessec/bryk/vendor/rails/activemodel/lib/active_model/attribute_registration.rb:38:in 'attribute_types'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/attribute_methods.rb:261:in '_has_attribute?'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/inheritance.rb:61:in 'new'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/persistence.rb:54:in 'create!'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/test/transaction_test_methods.rb:188:in 'test_using_named_savepoints'
     185:   def test_using_named_savepoints
     186:     omit 'savepoints not supported' unless @supports_savepoints
     187:
  => 188:     first = Entry.create! :title => '1'; first.reload
     189:
     190:     Entry.transaction do
     191:       first.content = 't'
org/jruby/RubyKernel.java:1409:in 'catch'
org/jruby/RubyKernel.java:1404:in 'catch'
org/jruby/RubyArray.java:2097:in 'each'
org/jruby/RubyArray.java:2097:in 'each'
org/jruby/RubyKernel.java:1409:in 'catch'
org/jruby/RubyKernel.java:1404:in 'catch'