Mssql, fix method internal_exec_query signature definition
Error: test_validate_uniqueness_by_default_database_collation(MSSQLValidationTest): ArgumentError: unknown keyword: :materialize_transactions
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/database_statements.rb:95:in 'internal_exec_query'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:117:in 'query'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb:113:in 'query_values'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:36:in 'data_sources'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:430:in 'block in tables_to_cache'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:459:in 'with_connection'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:429:in 'tables_to_cache'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:313:in 'data_source_exists?'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:38:in 'data_source_exists?'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/schema_cache.rb:182:in 'data_source_exists?'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/model_schema.rb:433:in 'table_exists?'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/attribute_methods/primary_key.rb:108:in 'get_primary_key'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/attribute_methods/primary_key.rb:97:in 'reset_primary_key'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/attribute_methods/primary_key.rb:81:in 'primary_key'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/core.rb:847:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/persistence.rb:847:in 'init_internals'
/home/jessec/bryk/vendor/rails/activemodel/lib/active_model/dirty.rb:373:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/attribute_methods/dirty.rb:197:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/timestamp.rb:103:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/associations.rb:78:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/autosave_association.rb:291:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/transactions.rb:459:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/touch_later.rb:50:in 'init_internals'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/core.rb:476:in 'initialize'
org/jruby/RubyClass.java:1050:in 'new'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/inheritance.rb:76:in 'new'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/test/db/mssql/validations_test.rb:56:in 'test_validate_uniqueness_by_default_database_collation'
     53:   def test_validate_uniqueness_by_default_database_collation
     54:     # Case insensitive, accent sensitive collation SQL_Latin1_General_CP1_CI_AS
     55:     # by default in not changed in the mssql server
  => 56:     topic1 = ValidationDefaultTest.new(name: "Hello world!")
     57:     topic2 = ValidationDefaultTest.new(name: "Hello world!")
     58:     topic3 = ValidationDefaultTest.new(name: "hello world!")
     59:
org/jruby/RubyKernel.java:1409:in 'catch'
org/jruby/RubyKernel.java:1404:in 'catch'
org/jruby/RubyArray.java:2097:in 'each'
org/jruby/RubyArray.java:2097:in 'each'
org/jruby/RubyKernel.java:1409:in 'catch'
org/jruby/RubyKernel.java:1404:in 'catch'