Mssql, fix undefined serialize error (due changes in schema creation)
Error: test_reset_column_information(MSSQLResetColumnInformationTest): NoMethodError: undefined method 'serialize' for nil
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb:151:in 'quote_default_expression'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/quoting.rb:129:in 'quote_default_expression'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:16:in 'quote_default_expression'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/schema_creation.rb:58:in 'add_column_options!'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:37:in 'visit_ColumnDefinition'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:13:in 'accept'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/schema_creation.rb:24:in 'block in visit_TableDefinition'
org/jruby/RubyArray.java:2896:in 'map'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/lib/arjdbc/mssql/schema_creation.rb:24:in 'visit_TableDefinition'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_creation.rb:13:in 'accept'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb:313:in 'create_table'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/migration/default_strategy.rb:10:in 'method_missing'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/migration.rb:1061:in 'block in method_missing'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/migration.rb:1027:in 'block in say_with_time'
/home/jessec/bryk/vendor/rails/activesupport/lib/active_support/benchmark.rb:17:in 'realtime'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/migration.rb:1027:in 'say_with_time'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/migration.rb:1050:in 'method_missing'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/migration.rb:582:in 'create_table'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/test/reset_column_info_test_methods.rb:43:in 'block in create_fhqwhgads_table_2!'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/migration.rb:1036:in 'suppress_messages'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/test/reset_column_info_test_methods.rb:42:in 'block in create_fhqwhgads_table_2!'
org/jruby/RubyBasicObject.java:2708:in 'instance_eval'
org/jruby/RubyBasicObject.java:2736:in 'instance_eval'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/schema.rb:56:in 'block in define'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:459:in 'with_connection'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/schema.rb:55:in 'define'
/home/jessec/bryk/vendor/rails/activerecord/lib/active_record/schema.rb:50:in 'define'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/test/reset_column_info_test_methods.rb:41:in 'create_fhqwhgads_table_2!'
/home/jessec/bryk/vendor/activerecord-jdbc-adapter/test/reset_column_info_test_methods.rb:13:in 'test_reset_column_information'
     10:     assert_equal ["id", "come_on"].sort, Fhqwhgad.columns.map{|c| c.name}.sort, "columns should be correct the first time"
     11:
     12:     drop_fhqwhgads_table!
  => 13:     create_fhqwhgads_table_2!
     14:     Fhqwhgad.reset_column_information
     15:     assert_equal ["id", "to_the_limit"].sort, Fhqwhgad.columns.map{|c| c.name}.sort, "columns should be correct the second time"
     16:   ensure
org/jruby/RubyKernel.java:1409:in 'catch'
org/jruby/RubyKernel.java:1404:in 'catch'
org/jruby/RubyArray.java:2097:in 'each'
org/jruby/RubyArray.java:2097:in 'each'
org/jruby/RubyKernel.java:1409:in 'catch'
org/jruby/RubyKernel.java:1404:in 'catch'